# kubernetes-deployment.yaml (for Google Kubernetes Engine)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-analyzer-backend
  labels:
    app: website-analyzer-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website-analyzer-backend
  template:
    metadata:
      labels:
        app: website-analyzer-backend
    spec:
      containers:
      - name: backend
        image: gcr.io/PROJECT_ID/website-analyzer-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: mongodb-url
        - name: DATABASE_NAME
          value: "lead-gen-ai-db"
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: gemini-api-key
        - name: GEMINI_MODEL
          value: "gemini-1.5-flash"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: secret-key
        - name: DEBUG
          value: "False"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: website-analyzer-backend-service
spec:
  selector:
    app: website-analyzer-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer